module.exports = {
    // GET
    titleKepalaSurat: '[data-cy="kepala-surat__title"]',
    closeKepalaSurat: '[data-cy="kepala-surat__close-button"]',
    titleTempatPenulisan: '[data-cy="kepala-surat__tempat-penulisan-title"]',
    inputTempatPenulisan: '[data-cy="kepala-surat__tempat-penulisan-input"]',
    //previewTempat: '[data-cy="surat__date-and-place"]',
    titleTanggal: '[data-cy="kepala-surat__tanggal-title"]',
    inputTanggal: '[data-cy="kepala-surat__tanggal-input"]',
    titleTujuan: '[data-cy="kepala-surat__tujuan__title"]',
    selectTujuan: '[data-cy="kepala-surat__tujuan__select-option"]',
    inputTujuan0: '[data-cy="kepala-surat__tujuan__select-option__custom-input0"]',
    inputTujuan1: '[data-cy="kepala-surat__tujuan__select-option__custom-input1"]',
    inputTujuan2: '[data-cy="kepala-surat__tujuan__select-option__custom-input2"]',
    inputTujuan3: '[data-cy="kepala-surat__tujuan__select-option__custom-input3"]',
    inputTujuan4: '[data-cy="kepala-surat__tujuan__select-option__custom-input4"]',
    inputTujuan5: '[data-cy="kepala-surat__tujuan__select-option__custom-input5"]',
    inputTujuanLampiran: '[data-cy="kepala-surat__tujuan__lampiran__input"]',
    addMoreTujuanLampiran: '[data-cy="lampiran-tujuan-surat__add-button"]',
    addMoreTujuan: '[data-cy="kepala-surat__tujuan__add-button"]',
    titleLokasi: '[data-cy="kepala-surat__lokasi__title"]',
    inputLokasi: '[data-cy="kepala-surat__lokasi__input"]',
    titleKodeKlasifikasi: '[data-cy="kepala-surat__kode-klasifikasi__title"]',
    selectKodeKlasifikasi: '[data-cy="kepala-surat__kode-klasifikasi__select-option"]',
    titleUnitPengolah: '[data-cy="kepala-surat__unit-pengolah__title"]',
    inputUnitPengolah: '[data-cy="kepala-surat__unit-pengolah__input"]',
    titleSifatSurat: '[data-cy="kepala-surat__sifat-surat__title"]',
    selectSifatSurat: '[data-cy="kepala-surat__sifat-surat__select-option"]',
    titleUrgensiSurat: '[data-cy="kepala-surat__urgensi__title"]',
    selectUrgensiSurat: '[data-cy="kepala-surat__urgensi__select-option"]',
    titlePerihal: '[data-cy="kepala-surat__perihal__title"]',
    inputPerihal: '[data-cy="kepala-surat__perihal__input"]',
    scrollForm: '[data-cy="surat__frame__input-kepala-surat"]',
    previewKepalaLampiran: '[data-cy="surat__kepala-surat"]',

    // XPATH
    previewTempat: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]',
    radio2: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/label[2]/input[1]',
    labelRadio2: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/label[2]',
    inputTujuanLampiran0: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/input[1]',
    inputTujuanLampiran1: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/input[1]',
    inputTujuanLampiran2: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/input[1]',
    inputTujuanLampiran3: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[4]/div[1]/div[1]/div[1]/input[1]',
    inputTujuanLampiran4: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[5]/div[1]/div[1]/div[1]/input[1]',
    inputTujuanLampiran5: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[6]/div[1]/div[1]/div[1]/input[1]',

}