module.exports = {
    // GET
    btnKirim: '[data-cy="surat-biasa-submit"]',
    titleKaki: '[data-cy="kaki-surat__title"]',
    closeKaki: '[data-cy="kaki-surat__close-button"]',
    closeKakiNotaDinas: '[data-cy="kaki-surat__close-btn"]',
    labelPenandatangan: '[data-cy="kaki-surat__penandatangan__label"]',
    labelPenandatanganNotaDinas: '[data-cy="kaki-surat__subtitle__penandatangan"]',
    selectPenandatangan: '[data-cy="kaki-surat__penandatangan__select-format"]',
    selectPenandatanganNotaDinas: '[data-cy="kaki-surat__penandatangan-select-format"]',
    pilihPenandatangan: '[data-cy="kaki-surat__penandatangan__select-option__custom-input0"]',
    pilihPenandatanganNotaDinas: '[data-cy="kaki-surat__penandatangan__v-select"]',
    labelPemeriksaNotaDinas: '[data-cy="kaki-surat__pemeriksa__subtitle"]',
    labelPemeriksa: '[data-cy="kaki-surat__pemeriksa__label"]',
    pilihPemeriksa: '[data-cy="kaki-surat__pemeriksa__select-option__custom-input0"]',
    pilihPemeriksa2: '[data-cy="kaki-surat__pemeriksa__select-option__custom-input1"]',
    pilihPemeriksaNotaDinas: '[data-cy="kaki-surat__pemeriksa__input-0"]',
    btnTambahPemeriksa: '[data-cy="kaki-surat__pemeriksa__add-button"]',
    btnTambahPemeriksaNotaDinas: '[data-cy="kaki-surat__pemeriksa__btn-add"]',
    labelTembusan: '[data-cy="kaki-surat__tembusan__label"]',
    subLabelTembusan: '[data-cy="kaki-surat__tembusan__description"]',
    pilihTembusan: '[data-cy="kaki-surat__tembusan__select-option__custom-input0"]',
    pilihTembusan2: '[data-cy="kaki-surat__tembusan__select-option__custom-input1"]',
    pilihTembusan3: '[data-cy="kaki-surat__tembusan__select-option__custom-input2"]',
    pilihTembusan4: '[data-cy="kaki-surat__tembusan__select-option__custom-input3"]',
    pilihTembusan5: '[data-cy="kaki-surat__tembusan__select-option__custom-input4"]',
    pilihTembusan6: '[data-cy="kaki-surat__tembusan__select-option__custom-input5"]',
    btnTambahTembusan: '[data-cy="kaki-surat__tembusan__add-button"]',
    // Nanti fungsi dibawah dipindah
    btnSimpanSurat: '[data-cy="surat-biasa-save"]',

    // XPATH
    selectedPenandatangan: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]',
    profileName: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/header[1]/div[2]/div[1]/div[1]/p[1]',
}