module.exports = {
    // GET
    titleKepalaSurat: '[data-cy="kepala-surat__title"]',
    closeKepalaSurat: '[data-cy="kepala-surat__close-button"]',
    titleTempatPenulisan: '[data-cy="kepala-surat__tempat-penulisan-title"]',
    inputTempatPenulisan: '[data-cy="kepala-surat__tempat-penulisan-input"]',
    titleTanggal: '[data-cy="kepala-surat__tanggal-title"]',
    inputTanggal: '[data-cy="kepala-surat__tanggal-input"]',
    titleTujuan: '[data-cy="kepala-surat__tujuan__title"]',
    subTitleTujuan: '[data-cy="kepala-surat__tujuan__subtitle"]',
    selectTujuan: '[data-cy="kepala-surat__tujuan__select-option"]',
    inputTujuan: '[data-cy="kepala-surat__tujuan__select-option__custom-input"]',
    addMoreTujuan: '[data-cy="kepala-surat__tujuan__add-button"]',
    titleLokasi: '[data-cy="kepala-surat__lokasi__title"]',
    inputLokasi: '[data-cy="kepala-surat__lokasi__input"]',
    titleKodeKlasifikasi: '[data-cy="kepala-surat__kode-klasifikasi__title"]',
    selectKodeKlasifikasi: '[data-cy="kepala-surat__kode-klasifikasi__select-option"]',
    titleUnitPengolah: '[data-cy="kepala-surat__unit-pengolah__title"]',
    inputUnitPengolah: '[data-cy="kepala-surat__unit-pengolah__input"]',
    titleSifatSurat: '[data-cy="kepala-surat__sifat-surat__title"]',
    selectSifatSurat: '[data-cy="kepala-surat__sifat-surat__select-option"]',
    titleUrgensiSurat: '[data-cy="kepala-surat__urgensi__title"]',
    selectUrgensiSurat: '[data-cy="kepala-surat__urgensi__select-option"]',
    titlePerihal: '[data-cy="kepala-surat__perihal__title"]',
    inputPerihal: '[data-cy="kepala-surat__perihal__input"]',

    // XPATH
    scrollForm: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]',
    previewTempat: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]',
}