module.exports = {
    // GET
    konsepNaskahMenu: '[data-cy="sidebar-menu-konsep-naskah"]',
    titleKonsepNaskah: '[data-cy="template-naskah__title"]',
    subTitleKonsepNaskah: '[data-cy="template-naskah__subtitle"]',
    suratBiasa: '[data-cy="template-naskah__surat-biasa"]',
    btnKembali: '[data-cy="surat-biasa-left-arrow"]',
    titleMenu: '[data-cy="surat-biasa-title"]',
    selectedKonsep: '[data-cy="surat-biasa-dropdown__surat-biasa"]',
    btnKirimNaskah: '[data-cy="surat-biasa-submit"]',
    editFormDefault: '[data-cy="surat-biasa-click-to-edit"]',
    previewKop: '[data-cy="surat__kop-surat"]',
    titleKop: '[data-cy="kop-surat__title"]',
    previewKepala: '[data-cy="surat__kepala-surat"]',
    titleKepala: '[data-cy="kepala-surat__title"]',
    previewBadan: '[data-cy="surat__badan-surat"]',
    titleBadan: '[data-cy="badan-naskah__title"]',
    previewKaki: '[data-cy="surat__kaki-surat"]',
    titleKaki: '[data-cy="kaki-surat__title"]',
    previewKepalaLampiran: '[data-cy="lampiran-tujuan-surat__title"]',


    // XPATH
    titleNaskahKeluar: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]',
    previewPage: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]',
    previewLampiran: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[2]',
    previewLampiran2: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[3]',
    titlePreviewLampiran: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[2]/div[1]/p[1]',
    btnBuatLampiran: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[2]/div[2]/button[1]',
    btnUploadFile: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[2]/div[2]/button[2]',
    titleBatalDrafting: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[3]/div[1]/header[1]/h5[1]/strong[1]',
    btnBatalDrafting: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[3]/div[1]/div[3]/div[1]/button[2]/div[1]/span[1]',
    btnLanjutkanDrafting: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[3]/div[1]/div[3]/div[1]/button[1]/div[1]/span[1]',
    titleLampiran: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/h2[1]',
    tableNaskahKeluar: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[1]/table[1]',
    kolomStatus: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[1]/table[1]/thead[1]/tr[1]/th[1]',
    kolomJenis: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[1]/table[1]/thead[1]/tr[1]/th[2]',
    kolomTujuan: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[1]/table[1]/thead[1]/tr[1]/th[3]',
    kolomUpdate: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[1]/table[1]/thead[1]/tr[1]/th[4]',
    konfirmasiKirimNaskah: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[3]/div[1]/div[4]/div[1]/button[2]',
    previewPageDown: '/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]'
}